### ISSUE TITLE
DEFAULT_MGM_KEY is not public

### ISSUE THREAD

**Issue by colemickens** [iqlusioninc/yubikey-piv.rs#156]
https://github.com/iqlusioninc/yubikey-piv.rs/blob/860c163eb9c70471aa842d59be96efa1f49485fb/src/mgm.rs#L61

seems like it ought to be public

**Comment by tarcieri** [comment]
It's available through the `Default` impl on `MgmKey`:

https://github.com/iqlusioninc/yubikey-piv.rs/blob/860c163eb9c70471aa842d59be96efa1f49485fb/src/mgm.rs#L308-#L312

**Comment by colemickens** [comment]
Thanks!
